services:
  task-analytics:
    build:
      context: ../../
      target: production
    ports:
      - "3003:3003"
    environment: # move to deployment/config
      NODE_ENV: production
      PORT: "3003"
      DATABASE_URL: ${DATABASE_URL} # set up as env secret
      RABBITMQ_URL: ${RABBITMQ_URL} # set up as env secret
      CORS_ORIGIN: ${CORS_ORIGIN:-*} # set up as env secret
    restart: unless-stopped
